CREATE ROLE oe_app LOGIN PASSWORD 'oe_password';

GRANT USAGE ON SCHEMA oe TO oe_app;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA oe
TO oe_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA oe
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLES
TO oe_app;