// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                     = new(Query)
	Kabupaten             *kabupaten
	Kecamatan             *kecamatan
	Kelurahan             *kelurahan
	Location              *location
	Province              *province
	TemplateTask          *templateTask
	TemplateTaskAttribute *templateTaskAttribute
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Kabupaten = &Q.Kabupaten
	Kecamatan = &Q.Kecamatan
	Kelurahan = &Q.Kelurahan
	Location = &Q.Location
	Province = &Q.Province
	TemplateTask = &Q.TemplateTask
	TemplateTaskAttribute = &Q.TemplateTaskAttribute
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                    db,
		Kabupaten:             newKabupaten(db, opts...),
		Kecamatan:             newKecamatan(db, opts...),
		Kelurahan:             newKelurahan(db, opts...),
		Location:              newLocation(db, opts...),
		Province:              newProvince(db, opts...),
		TemplateTask:          newTemplateTask(db, opts...),
		TemplateTaskAttribute: newTemplateTaskAttribute(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Kabupaten             kabupaten
	Kecamatan             kecamatan
	Kelurahan             kelurahan
	Location              location
	Province              province
	TemplateTask          templateTask
	TemplateTaskAttribute templateTaskAttribute
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Kabupaten:             q.Kabupaten.clone(db),
		Kecamatan:             q.Kecamatan.clone(db),
		Kelurahan:             q.Kelurahan.clone(db),
		Location:              q.Location.clone(db),
		Province:              q.Province.clone(db),
		TemplateTask:          q.TemplateTask.clone(db),
		TemplateTaskAttribute: q.TemplateTaskAttribute.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                    db,
		Kabupaten:             q.Kabupaten.replaceDB(db),
		Kecamatan:             q.Kecamatan.replaceDB(db),
		Kelurahan:             q.Kelurahan.replaceDB(db),
		Location:              q.Location.replaceDB(db),
		Province:              q.Province.replaceDB(db),
		TemplateTask:          q.TemplateTask.replaceDB(db),
		TemplateTaskAttribute: q.TemplateTaskAttribute.replaceDB(db),
	}
}

type queryCtx struct {
	Kabupaten             IKabupatenDo
	Kecamatan             IKecamatanDo
	Kelurahan             IKelurahanDo
	Location              ILocationDo
	Province              IProvinceDo
	TemplateTask          ITemplateTaskDo
	TemplateTaskAttribute ITemplateTaskAttributeDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Kabupaten:             q.Kabupaten.WithContext(ctx),
		Kecamatan:             q.Kecamatan.WithContext(ctx),
		Kelurahan:             q.Kelurahan.WithContext(ctx),
		Location:              q.Location.WithContext(ctx),
		Province:              q.Province.WithContext(ctx),
		TemplateTask:          q.TemplateTask.WithContext(ctx),
		TemplateTaskAttribute: q.TemplateTaskAttribute.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
