// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Customer        *customer
	LeasingContract *leasingContract
	LeasingProduct  *leasingProduct
	LeasingTask     *leasingTask
	LeasingTaskAtr  *leasingTaskAtr
	Motor           *motor
	MotorType       *motorType
	PaymentSchedule *paymentSchedule
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Customer = &Q.Customer
	LeasingContract = &Q.LeasingContract
	LeasingProduct = &Q.LeasingProduct
	LeasingTask = &Q.LeasingTask
	LeasingTaskAtr = &Q.LeasingTaskAtr
	Motor = &Q.Motor
	MotorType = &Q.MotorType
	PaymentSchedule = &Q.PaymentSchedule
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Customer:        newCustomer(db, opts...),
		LeasingContract: newLeasingContract(db, opts...),
		LeasingProduct:  newLeasingProduct(db, opts...),
		LeasingTask:     newLeasingTask(db, opts...),
		LeasingTaskAtr:  newLeasingTaskAtr(db, opts...),
		Motor:           newMotor(db, opts...),
		MotorType:       newMotorType(db, opts...),
		PaymentSchedule: newPaymentSchedule(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Customer        customer
	LeasingContract leasingContract
	LeasingProduct  leasingProduct
	LeasingTask     leasingTask
	LeasingTaskAtr  leasingTaskAtr
	Motor           motor
	MotorType       motorType
	PaymentSchedule paymentSchedule
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Customer:        q.Customer.clone(db),
		LeasingContract: q.LeasingContract.clone(db),
		LeasingProduct:  q.LeasingProduct.clone(db),
		LeasingTask:     q.LeasingTask.clone(db),
		LeasingTaskAtr:  q.LeasingTaskAtr.clone(db),
		Motor:           q.Motor.clone(db),
		MotorType:       q.MotorType.clone(db),
		PaymentSchedule: q.PaymentSchedule.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Customer:        q.Customer.replaceDB(db),
		LeasingContract: q.LeasingContract.replaceDB(db),
		LeasingProduct:  q.LeasingProduct.replaceDB(db),
		LeasingTask:     q.LeasingTask.replaceDB(db),
		LeasingTaskAtr:  q.LeasingTaskAtr.replaceDB(db),
		Motor:           q.Motor.replaceDB(db),
		MotorType:       q.MotorType.replaceDB(db),
		PaymentSchedule: q.PaymentSchedule.replaceDB(db),
	}
}

type queryCtx struct {
	Customer        ICustomerDo
	LeasingContract ILeasingContractDo
	LeasingProduct  ILeasingProductDo
	LeasingTask     ILeasingTaskDo
	LeasingTaskAtr  ILeasingTaskAtrDo
	Motor           IMotorDo
	MotorType       IMotorTypeDo
	PaymentSchedule IPaymentScheduleDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Customer:        q.Customer.WithContext(ctx),
		LeasingContract: q.LeasingContract.WithContext(ctx),
		LeasingProduct:  q.LeasingProduct.WithContext(ctx),
		LeasingTask:     q.LeasingTask.WithContext(ctx),
		LeasingTaskAtr:  q.LeasingTaskAtr.WithContext(ctx),
		Motor:           q.Motor.WithContext(ctx),
		MotorType:       q.MotorType.WithContext(ctx),
		PaymentSchedule: q.PaymentSchedule.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
