// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"github.com/codeid/honda-leasing-api/internal/domain/models"
)

func newLeasingTaskAtr(db *gorm.DB, opts ...gen.DOOption) leasingTaskAtr {
	_leasingTaskAtr := leasingTaskAtr{}

	_leasingTaskAtr.leasingTaskAtrDo.UseDB(db, opts...)
	_leasingTaskAtr.leasingTaskAtrDo.UseModel(&models.LeasingTaskAtr{})

	tableName := _leasingTaskAtr.leasingTaskAtrDo.TableName()
	_leasingTaskAtr.ALL = field.NewAsterisk(tableName)
	_leasingTaskAtr.TasaID = field.NewInt64(tableName, "tasa_id")
	_leasingTaskAtr.TasaName = field.NewString(tableName, "tasa_name")
	_leasingTaskAtr.TasaValue = field.NewString(tableName, "tasa_value")
	_leasingTaskAtr.TasaStatus = field.NewString(tableName, "tasa_status")
	_leasingTaskAtr.TasaTaskID = field.NewInt64(tableName, "tasa_task_id")
	_leasingTaskAtr.CreatedAt = field.NewTime(tableName, "created_at")

	_leasingTaskAtr.fillFieldMap()

	return _leasingTaskAtr
}

type leasingTaskAtr struct {
	leasingTaskAtrDo leasingTaskAtrDo

	ALL        field.Asterisk
	TasaID     field.Int64
	TasaName   field.String
	TasaValue  field.String
	TasaStatus field.String
	TasaTaskID field.Int64
	CreatedAt  field.Time

	fieldMap map[string]field.Expr
}

func (l leasingTaskAtr) Table(newTableName string) *leasingTaskAtr {
	l.leasingTaskAtrDo.UseTable(newTableName)
	return l.updateTableName(newTableName)
}

func (l leasingTaskAtr) As(alias string) *leasingTaskAtr {
	l.leasingTaskAtrDo.DO = *(l.leasingTaskAtrDo.As(alias).(*gen.DO))
	return l.updateTableName(alias)
}

func (l *leasingTaskAtr) updateTableName(table string) *leasingTaskAtr {
	l.ALL = field.NewAsterisk(table)
	l.TasaID = field.NewInt64(table, "tasa_id")
	l.TasaName = field.NewString(table, "tasa_name")
	l.TasaValue = field.NewString(table, "tasa_value")
	l.TasaStatus = field.NewString(table, "tasa_status")
	l.TasaTaskID = field.NewInt64(table, "tasa_task_id")
	l.CreatedAt = field.NewTime(table, "created_at")

	l.fillFieldMap()

	return l
}

func (l *leasingTaskAtr) WithContext(ctx context.Context) ILeasingTaskAtrDo {
	return l.leasingTaskAtrDo.WithContext(ctx)
}

func (l leasingTaskAtr) TableName() string { return l.leasingTaskAtrDo.TableName() }

func (l leasingTaskAtr) Alias() string { return l.leasingTaskAtrDo.Alias() }

func (l leasingTaskAtr) Columns(cols ...field.Expr) gen.Columns {
	return l.leasingTaskAtrDo.Columns(cols...)
}

func (l *leasingTaskAtr) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := l.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (l *leasingTaskAtr) fillFieldMap() {
	l.fieldMap = make(map[string]field.Expr, 6)
	l.fieldMap["tasa_id"] = l.TasaID
	l.fieldMap["tasa_name"] = l.TasaName
	l.fieldMap["tasa_value"] = l.TasaValue
	l.fieldMap["tasa_status"] = l.TasaStatus
	l.fieldMap["tasa_task_id"] = l.TasaTaskID
	l.fieldMap["created_at"] = l.CreatedAt
}

func (l leasingTaskAtr) clone(db *gorm.DB) leasingTaskAtr {
	l.leasingTaskAtrDo.ReplaceConnPool(db.Statement.ConnPool)
	return l
}

func (l leasingTaskAtr) replaceDB(db *gorm.DB) leasingTaskAtr {
	l.leasingTaskAtrDo.ReplaceDB(db)
	return l
}

type leasingTaskAtrDo struct{ gen.DO }

type ILeasingTaskAtrDo interface {
	gen.SubQuery
	Debug() ILeasingTaskAtrDo
	WithContext(ctx context.Context) ILeasingTaskAtrDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() ILeasingTaskAtrDo
	WriteDB() ILeasingTaskAtrDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) ILeasingTaskAtrDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) ILeasingTaskAtrDo
	Not(conds ...gen.Condition) ILeasingTaskAtrDo
	Or(conds ...gen.Condition) ILeasingTaskAtrDo
	Select(conds ...field.Expr) ILeasingTaskAtrDo
	Where(conds ...gen.Condition) ILeasingTaskAtrDo
	Order(conds ...field.Expr) ILeasingTaskAtrDo
	Distinct(cols ...field.Expr) ILeasingTaskAtrDo
	Omit(cols ...field.Expr) ILeasingTaskAtrDo
	Join(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo
	LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo
	RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo
	Group(cols ...field.Expr) ILeasingTaskAtrDo
	Having(conds ...gen.Condition) ILeasingTaskAtrDo
	Limit(limit int) ILeasingTaskAtrDo
	Offset(offset int) ILeasingTaskAtrDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskAtrDo
	Unscoped() ILeasingTaskAtrDo
	Create(values ...*models.LeasingTaskAtr) error
	CreateInBatches(values []*models.LeasingTaskAtr, batchSize int) error
	Save(values ...*models.LeasingTaskAtr) error
	First() (*models.LeasingTaskAtr, error)
	Take() (*models.LeasingTaskAtr, error)
	Last() (*models.LeasingTaskAtr, error)
	Find() ([]*models.LeasingTaskAtr, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTaskAtr, err error)
	FindInBatches(result *[]*models.LeasingTaskAtr, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*models.LeasingTaskAtr) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) ILeasingTaskAtrDo
	Assign(attrs ...field.AssignExpr) ILeasingTaskAtrDo
	Joins(fields ...field.RelationField) ILeasingTaskAtrDo
	Preload(fields ...field.RelationField) ILeasingTaskAtrDo
	FirstOrInit() (*models.LeasingTaskAtr, error)
	FirstOrCreate() (*models.LeasingTaskAtr, error)
	FindByPage(offset int, limit int) (result []*models.LeasingTaskAtr, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) ILeasingTaskAtrDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (l leasingTaskAtrDo) Debug() ILeasingTaskAtrDo {
	return l.withDO(l.DO.Debug())
}

func (l leasingTaskAtrDo) WithContext(ctx context.Context) ILeasingTaskAtrDo {
	return l.withDO(l.DO.WithContext(ctx))
}

func (l leasingTaskAtrDo) ReadDB() ILeasingTaskAtrDo {
	return l.Clauses(dbresolver.Read)
}

func (l leasingTaskAtrDo) WriteDB() ILeasingTaskAtrDo {
	return l.Clauses(dbresolver.Write)
}

func (l leasingTaskAtrDo) Session(config *gorm.Session) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Session(config))
}

func (l leasingTaskAtrDo) Clauses(conds ...clause.Expression) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Clauses(conds...))
}

func (l leasingTaskAtrDo) Returning(value interface{}, columns ...string) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Returning(value, columns...))
}

func (l leasingTaskAtrDo) Not(conds ...gen.Condition) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Not(conds...))
}

func (l leasingTaskAtrDo) Or(conds ...gen.Condition) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Or(conds...))
}

func (l leasingTaskAtrDo) Select(conds ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Select(conds...))
}

func (l leasingTaskAtrDo) Where(conds ...gen.Condition) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Where(conds...))
}

func (l leasingTaskAtrDo) Order(conds ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Order(conds...))
}

func (l leasingTaskAtrDo) Distinct(cols ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Distinct(cols...))
}

func (l leasingTaskAtrDo) Omit(cols ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Omit(cols...))
}

func (l leasingTaskAtrDo) Join(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Join(table, on...))
}

func (l leasingTaskAtrDo) LeftJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.LeftJoin(table, on...))
}

func (l leasingTaskAtrDo) RightJoin(table schema.Tabler, on ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.RightJoin(table, on...))
}

func (l leasingTaskAtrDo) Group(cols ...field.Expr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Group(cols...))
}

func (l leasingTaskAtrDo) Having(conds ...gen.Condition) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Having(conds...))
}

func (l leasingTaskAtrDo) Limit(limit int) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Limit(limit))
}

func (l leasingTaskAtrDo) Offset(offset int) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Offset(offset))
}

func (l leasingTaskAtrDo) Scopes(funcs ...func(gen.Dao) gen.Dao) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Scopes(funcs...))
}

func (l leasingTaskAtrDo) Unscoped() ILeasingTaskAtrDo {
	return l.withDO(l.DO.Unscoped())
}

func (l leasingTaskAtrDo) Create(values ...*models.LeasingTaskAtr) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Create(values)
}

func (l leasingTaskAtrDo) CreateInBatches(values []*models.LeasingTaskAtr, batchSize int) error {
	return l.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (l leasingTaskAtrDo) Save(values ...*models.LeasingTaskAtr) error {
	if len(values) == 0 {
		return nil
	}
	return l.DO.Save(values)
}

func (l leasingTaskAtrDo) First() (*models.LeasingTaskAtr, error) {
	if result, err := l.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAtr), nil
	}
}

func (l leasingTaskAtrDo) Take() (*models.LeasingTaskAtr, error) {
	if result, err := l.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAtr), nil
	}
}

func (l leasingTaskAtrDo) Last() (*models.LeasingTaskAtr, error) {
	if result, err := l.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAtr), nil
	}
}

func (l leasingTaskAtrDo) Find() ([]*models.LeasingTaskAtr, error) {
	result, err := l.DO.Find()
	return result.([]*models.LeasingTaskAtr), err
}

func (l leasingTaskAtrDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*models.LeasingTaskAtr, err error) {
	buf := make([]*models.LeasingTaskAtr, 0, batchSize)
	err = l.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (l leasingTaskAtrDo) FindInBatches(result *[]*models.LeasingTaskAtr, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return l.DO.FindInBatches(result, batchSize, fc)
}

func (l leasingTaskAtrDo) Attrs(attrs ...field.AssignExpr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Attrs(attrs...))
}

func (l leasingTaskAtrDo) Assign(attrs ...field.AssignExpr) ILeasingTaskAtrDo {
	return l.withDO(l.DO.Assign(attrs...))
}

func (l leasingTaskAtrDo) Joins(fields ...field.RelationField) ILeasingTaskAtrDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Joins(_f))
	}
	return &l
}

func (l leasingTaskAtrDo) Preload(fields ...field.RelationField) ILeasingTaskAtrDo {
	for _, _f := range fields {
		l = *l.withDO(l.DO.Preload(_f))
	}
	return &l
}

func (l leasingTaskAtrDo) FirstOrInit() (*models.LeasingTaskAtr, error) {
	if result, err := l.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAtr), nil
	}
}

func (l leasingTaskAtrDo) FirstOrCreate() (*models.LeasingTaskAtr, error) {
	if result, err := l.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*models.LeasingTaskAtr), nil
	}
}

func (l leasingTaskAtrDo) FindByPage(offset int, limit int) (result []*models.LeasingTaskAtr, count int64, err error) {
	result, err = l.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = l.Offset(-1).Limit(-1).Count()
	return
}

func (l leasingTaskAtrDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = l.Count()
	if err != nil {
		return
	}

	err = l.Offset(offset).Limit(limit).Scan(result)
	return
}

func (l leasingTaskAtrDo) Scan(result interface{}) (err error) {
	return l.DO.Scan(result)
}

func (l leasingTaskAtrDo) Delete(models ...*models.LeasingTaskAtr) (result gen.ResultInfo, err error) {
	return l.DO.Delete(models)
}

func (l *leasingTaskAtrDo) withDO(do gen.Dao) *leasingTaskAtrDo {
	l.DO = *do.(*gen.DO)
	return l
}
