// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"
)

const TableNameCountry = "countries"

// Country mapped from table <countries>
type Country struct {
	CountryID    string     `gorm:"column:country_id;type:character(2);primaryKey" json:"country_id"`
	CountryName  *string    `gorm:"column:country_name;type:character varying(40)" json:"country_name"`
	RegionID     int64      `gorm:"column:region_id;type:bigint;not null" json:"region_id"`
	CreatedDate  *time.Time `gorm:"column:created_date;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"created_date"`
	ModifiedDate *time.Time `gorm:"column:modified_date;type:timestamp without time zone;default:CURRENT_TIMESTAMP" json:"modified_date"`
}

// TableName Country's table name
func (*Country) TableName() string {
	return TableNameCountry
}
