// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameMotorType = "dealer.motor_types"

// MotorType mapped from table <dealer.motor_types>
type MotorType struct {
	MotyID   int64  `gorm:"column:moty_id;type:bigint;primaryKey;autoIncrement:true" json:"moty_id"`
	MotyName string `gorm:"column:moty_name;type:character varying(55);not null" json:"moty_name"`
}

// TableName MotorType's table name
func (*MotorType) TableName() string {
	return TableNameMotorType
}
